# Generated by Django 3.2.12 on 2022-05-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('admno', models.IntegerField()),
                ('department', models.CharField(max_length=200, null=True)),
                ('year', models.IntegerField()),
                ('course', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('contactno', models.IntegerField()),
            ],
        ),
    ]
