# Generated by Django 3.2.12 on 2022-05-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_parreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='addteach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('tid', models.IntegerField()),
                ('department', models.CharField(max_length=200, null=True)),
                ('course', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('contactno', models.IntegerField()),
            ],
        ),
    ]
