# Generated by Django 3.2.12 on 2022-05-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_addteach'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=200, null=True)),
                ('date', models.DateField()),
                ('day', models.IntegerField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
