# Generated by Django 3.2.12 on 2022-05-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='addteach',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addteach',
            name='contactno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addteach',
            name='tid',
            field=models.IntegerField(null=True),
        ),
    ]
