# Generated by Django 3.2.12 on 2022-06-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
