# Generated by Django 3.2.12 on 2022-06-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20220611_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='admno',
            field=models.IntegerField(null=True),
        ),
    ]
