# Generated by Django 3.2.12 on 2022-06-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_leave_admno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studreg'),
        ),
    ]
