# Generated by Django 3.2.12 on 2022-06-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_leave_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parreg',
            name='sname',
        ),
        migrations.AlterField(
            model_name='leave',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
