# Generated by Django 4.0.4 on 2022-07-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_parreg_sname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parreg',
            old_name='sid',
            new_name='spi',
        ),
        migrations.AddField(
            model_name='studreg',
            name='spi',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
