# Generated by Django 4.0.4 on 2022-07-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_rename_spi_parreg_sid_remove_studreg_spi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parreg',
            old_name='sid',
            new_name='admno',
        ),
    ]
