# Generated by Django 4.0.4 on 2022-07-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_rename_sid_parreg_admno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studreg',
            old_name='username',
            new_name='sname',
        ),
    ]
