# Generated by Django 4.0.4 on 2022-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_rename_username_studreg_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
