# Generated by Django 4.0.4 on 2022-07-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_eventadd_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='parreg',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
